/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const NoteId = IDL.Nat;
export const Time = IDL.Int;
export const Note = IDL.Record({
  'noteId' : NoteId,
  'date' : IDL.Text,
  'hour' : IDL.Nat,
  'note' : IDL.Text,
  'timestamp' : Time,
});

export const idlService = IDL.Service({
  'createNote' : IDL.Func([IDL.Text, IDL.Nat, IDL.Text], [], []),
  'deleteNote' : IDL.Func([IDL.Nat], [], []),
  'getAllNotes' : IDL.Func([], [IDL.Vec(Note)], ['query']),
  'getNoteById' : IDL.Func([IDL.Nat], [Note], ['query']),
  'getNotesByDate' : IDL.Func([IDL.Text], [IDL.Vec(Note)], ['query']),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const NoteId = IDL.Nat;
  const Time = IDL.Int;
  const Note = IDL.Record({
    'noteId' : NoteId,
    'date' : IDL.Text,
    'hour' : IDL.Nat,
    'note' : IDL.Text,
    'timestamp' : Time,
  });
  
  return IDL.Service({
    'createNote' : IDL.Func([IDL.Text, IDL.Nat, IDL.Text], [], []),
    'deleteNote' : IDL.Func([IDL.Nat], [], []),
    'getAllNotes' : IDL.Func([], [IDL.Vec(Note)], ['query']),
    'getNoteById' : IDL.Func([IDL.Nat], [Note], ['query']),
    'getNotesByDate' : IDL.Func([IDL.Text], [IDL.Vec(Note)], ['query']),
  });
};

export const init = ({ IDL }) => { return []; };